### ISSUE TITLE
TOPP_tutorial not properly rendered to pdf

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1755]
```
Some pages of the tutorial (http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/TOPP_tutorial.pdf) are not correctly displayed in my pdf reader 
(especially chapter 4 and chapter 6) as the right part of the text is missing (lines too long). 
Is this an issue with my Acrobat reader or can you correct this.
```

**Comment by hroest** [comment]
same with evince ...

**Comment by jpfeuffer** [comment]
http://doxygen.10944.n7.nabble.com/Markdown-Images-and-paragraph-indentations-td5995.html

**Comment by jpfeuffer** [comment]
I don't really know Doxygens Syntax very well but it adds this DoxyVerb environment for some reason.

**Comment by jpfeuffer** [comment]
Maybe it is because of that double newline? I'll do a short test on the linux build machine.
https://github.com/OpenMS/OpenMS/blob/develop/doc/TOPP_tutorial/TOPPAS.doxygen#L56

**Comment by jpfeuffer** [comment]
No it was that the introduction section started with a tab, which is converted to 4 spaces and indentation with 4 spaces is a code block in doxygen's markdown.
In general I think all of our doxygen files need an overhaul. The TOPPAS one was an indentation hell. I fixed the most prominent errors but some paragraphs still look weirdly indented.

**Comment by jpfeuffer** [comment]
In the scripting part there is html markup that is not rendered properly as another example.

**Comment by jpfeuffer** [comment]
Ah no. It's the same "code block" error.

**Comment by jpfeuffer** [comment]
see #2437

**Comment by hroest** [comment]
this is still an issue for http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/TOPP_tutorial.pdf but is fixed for the develop version:http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/TOPP_tutorial.pdf -- 

can somebody replace the ill-formed pdf with the correct one and close the issue @jpfeuffer  ?

**Comment by hroest** [comment]
@jpfeuffer it seems the pdf at least is fixed, can we just replace the ill formed pdf

http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/TOPP_tutorial.pdf 

with this one

http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/TOPP_tutorial.pdf 

and the close this issue and discuss the rest in #550 ?

**Comment by jpfeuffer** [comment]
Okay. Done.
