### ISSUE TITLE
2D, 3D view with MALDI mzxml files

### ISSUE THREAD

**Issue by Berni133** [OpenMS/OpenMS#3228]
[archive.zip](https://github.com/OpenMS/OpenMS/files/1700546/archive.zip)

Hi! Is there a possivility to add a retention time manually to a mzxml file to view them also in 2D and 3D view? My MZXML is attetched.

Thanks a lot in advance!

**Comment by hroest** [comment]
Well you only have a single spectrum, so there is no 2D or 3D view for that. But what you can do is add retention time using pyopenms:

```
$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopenms
>>> e = pyopenms.MSExperiment()
>>> pyopenms.MzMLFile().load("D6_MS_1.mzxml", e)
>>> s = e.getSpectra()
>>> s[0].setRT(42)
>>> e.setSpectra(s)
>>> pyopenms.MzMLFile().store("D6_MS_1.fix.mzml", e)
```

if you do this for all your files and then merge them (or use pyopenms to store them all in a big MSExperiment) then you can view them:

```
>>> spec = s[0]
>>> e2 = pyopenms.MSExperiment()
>>> e2.addSpectrum(spec)
>>> spec.setRT(43)
>>> e2.addSpectrum(spec)
>>> spec.setRT(44)
>>> e2.addSpectrum(spec)
>>> pyopenms.MzMLFile().store("D6_MS_1.forFun.mzml", e2)
```

now open this file in TOPPView:

![screenshot from 2018-02-06 18-59-06](https://user-images.githubusercontent.com/464014/35890957-deb94482-0b6f-11e8-92ea-0fcdc0de0053.png)

of course showing 3x the same spectrum is quite beside the point but I assume you have more spectra :-)

**Comment by Berni133** [comment]
Thank you a lot. It works great!!!

PS:
I had to switch to Linux because the latest version of pyopenms  does not work on Windows.

**Comment by hroest** [comment]
> I had to switch to Linux because the latest version of pyopenms does not work on Windows.

are you using Python 2.7? We do not support the newest versions of pyopenms any more for Python 2.7 unfortunately. You can still install it with 

```
pip install pyopenms==2.1.0
```

**Comment by hroest** [comment]
PS: the windows install should now work out of the box, even though you will only be able to install an older version (2.1.0) if you are using Python 2.7

**Comment by Berni133** [comment]
It worked for me several times but now I always get the following error:

Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopenms
>>> e = pyopenms.MSExperiment()
>>> pyopenms.MzMLFile().load("D6_MS_1.mzxml", e)
/home/hr/openmsall/source/OpenMS-Release2.1.0/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp(103): While loading 'E9_MS_1.mzxml': Required attribute 'id' not present!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms/pyopenms.pyx", line 47367, in pyopenms.pyopenms.MzMLFile.load (pyopenms/pyopenms.cpp:947418)
RuntimeError: - due to that error of type Parse Error in: /home/hr/openmsall/source/OpenMS-Release2.1.0/src/openms/source/FORMAT/HANDLERS/XMLHandler.cpp@104-void OpenMS::Internal::XMLHandler::fatalError(OpenMS::Internal::XMLHandler::ActionMode, const OpenMS::String&, OpenMS::UInt, OpenMS::UInt) const

Does anyone have a suggestion. It would be very helpful.
Thanks

**Comment by hroest** [comment]
which pyopenms version and file is this? it looks like there is an issue with the file 

> While loading 'E9_MS_1.mzxml': Required attribute 'id' not present!

**Comment by Berni133** [comment]
Dear hroest!
First of all thank you for your great help!
Unforunately I still have a problem. I get an error massage: _Required attribute 'id' not present!_
Do you have any suggestions? 

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopenms
>>> e = pyopenms.MSExperiment()
>>> pyopenms.MzMLFile().load("D6_MS_1.mzxml", e)
C:\openms\src2.2\OpenMS-Release2.2.0\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp(110): While loading 'D6_MS_1.mzxml': Required attribute 'id' not present!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyopenms\pyopenms.pyx", line 36873, in pyopenms.pyopenms.MzMLFile.load
RuntimeError: - due to that error of type Parse Error in: C:\openms\src2.2\OpenMS-Release2.2.0\src\openms\source\FORMAT\HANDLERS\XMLHandler.cpp@111-void __cdecl OpenMS::Internal::XMLHandler::fatalError(enum OpenMS::Internal::XMLHandler::ActionMode,const class OpenMS::String &,unsigned int,unsigned int) const
>>>
```

**Comment by Berni133** [comment]
Dear hroest, dear jpfeuffer,

Thank you again for your help. Everything works now 👍.  I´m happy.

**Comment by jpfeuffer** [comment]
Great to hear! Did you reopen by accident? Otherwise it is fine for us if you close it.

**Comment by Berni133** [comment]
Thank you again for your great help it works now and I´m very happy. 

Maybe one last question: Is there also a possibility to add identifications manally. With an idXML file? I tried to read the documentataion, but I´m not sure if i read the right part.
