### ISSUE TITLE
conda builds not working anymore

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6514]
https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/conda/475/console

no idea why.

**Comment by jpfeuffer** [comment]
Issue nr2: our builds do not show the correct outcome 

```
Mamba failed to solve:
 - pandas
 - boost-cpp 1.74.0.*
 - python 3.7.* *_cpython
 - numpy 1.17.*
 - autowrap >=0.22.10
 - qt 5.12.*
 - wheel
 - libgcc-ng >=12
 - cython >=0.25.2
 - xerces-c 3.2.*
 - pip
 - libstdcxx-ng >=12
 - libsvm 3.21.*
 - setuptools
 - libopenms 3.0.0dev

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested libopenms 3.0.0dev
- 
Returning non-final recipe for pyopenms-3.0.0dev-py37_0; one or more dependencies was unsatisfiable:
19:01:25 CONDA_BUILD WARNING Returning non-final recipe for pyopenms-3.0.0dev-py37_0; one or more dependencies was unsatisfiable:
Reloading output folder: /home/builder/mambaforge/envs/bioconda/conda-bld
Transaction
```

**Comment by poshul** [comment]
Where do you see those errors? I see https://abibuilder.cs.uni-tuebingen.de/jenkins/job/openms/job/ntly/job/conda/477/  looking successful.

**Comment by timosachsenberg** [comment]
its in the console output

**Comment by timosachsenberg** [comment]
fixed with:
https://github.com/OpenMS/bioconda-recipes/pull/4

**Comment by jpfeuffer** [comment]
TODO:
- rewrite Jenkins script to save the exit code of the builds and report accordingly.
- build more python versions

**Comment by jpfeuffer** [comment]
Can you  check if you can read that from somewhere in the repo. Due to issues with the nightly wheels and different versions on Ubuntu,macOS,Win, I would like to fix a supported version file somewhere

**Comment by jpfeuffer** [comment]
For the time being add 3.9, 3.10, 3.11

**Comment by jpfeuffer** [comment]
Reduced to "major". It works now but the build statuses are still wrong.

**Comment by timosachsenberg** [comment]
is the build status still an issue?

**Comment by jpfeuffer** [comment]
Yes

**Comment by timosachsenberg** [comment]
I briefly checked. The return value of the anaconda upload in our /jenkins/job/openms/job/ntly/job/conda job is 1.

hope this is not related to the storage limits https://github.com/Anaconda-Platform/anaconda-client/issues/501#issuecomment-669237956

Any insights here?

**Comment by jpfeuffer** [comment]
Weird, tells me sth different:
openms-meta built: 1
pyopenms built: 1
upload: 0

**Comment by timosachsenberg** [comment]
ups sorry for the confusion you are right. so the upload worked but builds returned 1.

**Comment by jpfeuffer** [comment]
yes, as discussed because bioconda build is bugged

**Comment by jpfeuffer** [comment]
`06:55:31 BIOCONDA ERROR BUILD FAILED: the built package /home/builder/mambaforge/envs/bioconda/conda-bld/linux-64/pyopenms-3.0.0dev-py310h4b47abe_0.tar.bz2 cannot be found`

**Comment by timosachsenberg** [comment]
but it seems to upload it???

**Comment by jpfeuffer** [comment]
yes because it's bugged. bioconda build does not do the upload.

**Comment by jpfeuffer** [comment]
Someone NEEDS to file a bug report.

**Comment by bernt-matthias** [comment]
Wild guess: conda's has a new package format? Packages now end with `.conda`.

**Comment by jpfeuffer** [comment]
Hmm good guess, but it failed since years. It never worked to build inside a container when specifying you own repository.

**Comment by jpfeuffer** [comment]
This actually broke the builds completely. Seems like the env needs to be empty and due to the soft link, it is not anymore.

**Comment by poshul** [comment]
Okay, I've rolled that back. With Timo's update the Job should pass now even if the upload fails. Is that sufficient as a stopgap until we get a response from the bioconda folks?

**Comment by jpfeuffer** [comment]
But the update from Timo now only checks upload. And upload will always work because there is an artifact from a previous build. So we don't see any failures ever. There must be another way:
1. Parse logs
2. make upload fail if build fails (e.g. by checking date or resetting build folder [be careful with that, conda is very picky about folders used as environments])

**Comment by poshul** [comment]
https://github.com/bioconda/bioconda-utils/pull/838
