### ISSUE TITLE
InternalCalibration fails due to SageAdapter's idXML files storing RT as minutes

### ISSUE THREAD

**Issue by elrubio** [OpenMS/OpenMS#7119]
`Version: 3.1.0-pre-nightly-2023-10-08 Oct  8 2023, 23:03:49, Revision: 342f652`

In the idXML files coming out of `SageAdapter`, spectrum RT values are stored as *minutes*. This corresponds to how `sage` stores RT values in its PIN output files. 

But when I try to use such a file for calibration, it fails:

> **InternalCalibration -in file.mzML -out file.mzML -cal:id_in file.idXML -RT_chunking 1 -ms_level 1 -goodness:median 0.5 -goodness:MAD 1 -cal:model_type linear_weighted**
> [...]
> **Calibration failed on 42537/42771 [99 %] spectra**. Using the closest successful model on these.
> [...]
> ppm stats before calibration: median = -8.87936  MAD = 1.01739
> ppm stats after calibration: median = -0.941084  MAD = 0.868612
> Post calibration median threshold (0.5 ppm) not reached (median = |-0.941084| ppm). Failed to calibrate!
> 
> **Calibration failed. See error message above!**

When I edit the idXML file, converting minutes to seconds, calibration works as expected:

> [...]
> **Calibration failed on 13665/42771 [31 %] spectra**. Using the closest successful model on these.
> [...]
> ppm stats before calibration: median = -8.87936  MAD = 1.01739
> ppm stats after calibration: median = -0.000207935  MAD = 0.316614
> 42771 spectra and 3 chromatograms stored.

For idXML files, the unit for RT seems to be unspecified. At least I couldn't find anything in the schema. But since most RT-related parameters in TOPP tools accept *seconds* (including *-RT_chunking* above), I guess *seconds* is the default time unit in idXML files? If so, then `SageAdapter` should probably write out seconds, too. At the moment, its output files are not suitable for subsequent use with Calibration. I hope I didn't overlook something obvious.

**Comment by timosachsenberg** [comment]
Unit in idxml should always be seconds. I wonder if Sage parses the rt unit of the mzml file. E.g. if not this should be fixed in sage.

**Comment by jpfeuffer** [comment]
Yes, I am pretty sure we convert minutes to seconds in the loader:
https://github.com/OpenMS/OpenMS/blob/061c0e67ac26ad7917dbd3181af42b77a33ee170/src/openms/source/FORMAT/PercolatorInfile.cpp#L183
Unless we overwrite it later somewhere or Sage does not always write minutes, this should be fine.

**Comment by timosachsenberg** [comment]
which branch is this?
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/PercolatorInfile.cpp#L170
does not contain this conversion
was that an oversight or did you fix something here:
https://github.com/OpenMS/OpenMS/blame/develop/src/openms/source/FORMAT/PercolatorInfile.cpp#L170

**Comment by jpfeuffer** [comment]
Oh. Yes I fixed stuff at some point. Did I forget to commit/merge?

Timo Sachsenberg ***@***.***> schrieb am Do., 12. Okt. 2023,
17:33:

**Comment by jpfeuffer** [comment]
Or maybe I reverted because I suddenly had a file with a different unit?
So maybe it is indeed a bug in sage that they just print whatever is in the
mzml, not a specific unit.

Julianus Pfeuffer ***@***.***> schrieb am Do., 12. Okt. 2023, 17:45:

**Comment by elrubio** [comment]
The corresponding mzML contains _seconds_.

**Comment by jpfeuffer** [comment]
Ok! So if the mzml contains seconds and sage still writes minutes, I assume
there is logic inside that always write RT as minutes.

Therefore, I think we should always do the conversion to seconds, right
@timosachsenberg?

Alexander Haupt ***@***.***> schrieb am Do., 12. Okt. 2023,
17:52:

**Comment by timosachsenberg** [comment]
based on that: let's fix and see... Do you want to double check if you forgot a merge and do the change? Otherwise, I will do the one-liner.

**Comment by elrubio** [comment]
I have to correct myself: my original mzML files actually do contain *minutes*. I was fooled by the fact that the files coming out of `InternalCalibration` then have their rt values changed to *seconds*, I was looking at those.

In addition, I couldn't find any time modification in the `sage` code, so it looks indeed as if sage uses the time values *as is*. I will confirm this tomorrow. 

Nevertheless, the route `thermo-raw-file -> FileConverter -> SageAdapter -> InternalCalibration -> calibrated-rawfile` seems broken (at least here with Thermo raw files) due to this RT unit issue. 

One could argue that `sage` should output its time values in a consistent manner (I can ask). Another option would be that `SageAdapter` reads the time unit from the mzML it passes on to sage and then interprets the time data accordingly?

Side question: does the standard actually require all scans to have the same unit?

**Comment by timosachsenberg** [comment]
@lazear would it be an option to read the unit in sage and always use seconds (or minutes)

**Comment by lazear** [comment]
Definitely something that can be done - is this already done in OpenMS somewhere, or do you know off-hand which units are actually commonly observed in mzML's (e.g. second, minute, etc - do I need to support millisecond, hour, as well?)

**Comment by timosachsenberg** [comment]
I only saw seconds and minutes:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L2187-L2196

workarounds we had to add for some files:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L2219-L2229
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1218-L1221

**Comment by cbielow** [comment]
according to PSI-MS, units are limited to `sec` and `minutes`.
https://github.com/HUPO-PSI/psi-ms-CV/blob/d1ddcc9ac7f8c35e6b6d7c4efdd3a4574b5b0b3b/psi-ms.obo#L305

**Comment by timosachsenberg** [comment]
@lazear would resorting to seconds for the pin file be your preference? asking because then I can already finalize that part

**Comment by lazear** [comment]
@timosachsenberg let's do minutes, if that works?

**Comment by timosachsenberg** [comment]
Thanks! We will test a new release.

**Comment by poshul** [comment]
Thanks @lazear! Do you know when we should expect the next Sage release?

**Comment by lazear** [comment]
Now 😄

**Comment by timosachsenberg** [comment]
Thanks! I leave this issue open until we updated our thirdparties

**Comment by timosachsenberg** [comment]
TODO:

- [x] update in openms bioconda recipe (https://github.com/bioconda/bioconda-recipes/pull/43971)
- [x] update in thirdparty ([feature/sage_0144](https://github.com/OpenMS/THIRDPARTY/pull/105))

**Comment by mr-c** [comment]
Can someone add a test to confirm the fix so we can close this issue?

**Comment by timosachsenberg** [comment]
will close as it is probably fixed.
